version: '3.9'
services:
  front:
    container_name: node_front
    build: 
      context: ./fron-end
    ports:
      - 3000:3000
    command: sh -c 'npm run dev'
    volumes:
      - ./front-end/:/app
  back:
    container_name: node_back
    build: 
      context: ./back-end
    ports:
      - 3333:3333
    command: sh -c 'npm run dev'
    volumes:
      - ./back-end/:/app